# Generated by Django 3.2.12 on 2022-02-13 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='current_status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_count', models.SmallIntegerField()),
                ('temper', models.DecimalField(decimal_places=1, max_digits=3)),
                ('humi', models.DecimalField(decimal_places=1, max_digits=3)),
            ],
        ),
        migrations.CreateModel(
            name='temperature',
            fields=[
                ('date', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('temper', models.IntegerField()),
                ('humi', models.IntegerField()),
            ],
        ),
    ]
